# Generated by Django 5.1.6 on 2025-03-09 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
