services:
  redis:
    image: redis
    restart: always
    volumes:
        - ./data/redis:/data # bind mount the data so that it persists even if the container is removed
    container_name: redis_container


  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data # bind mount the data so that it persists even if the container is removed
    environment:
      - DJANGO_SETTINGS_MODULE=rpl.settings
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db


  rpl:
    build: . # current folder
    restart: always
    volumes:
      - .:/app # bind mount the current directory to /app in the container
    image: app:django # name of the image
    container_name: django_container # name of the container
    command: >
      bash -c "
        ./scripts/wait-for-it.sh db:5432 &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        uwsgi --ini /app/config/uwsgi/uwsgi.ini
      "
    environment:
      - DJANGO_SETTINGS_MODULE=rpl.settings
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - EMAIL_HOST_USER=rpl.etec@gmail.com
      - EMAIL_HOST_PASSWORD=wxfq qqau xvgp hhhy
      - DEFAULT_FROM_EMAIL=RPL <rpl.etec@gmail.com>
    depends_on:
      - db

  celery:
    restart: always
    build:
      context: .
    command: ["./scripts/wait-for-it.sh", "db:5432", "--",
              "celery", "-A", "rpl", "worker", "--loglevel=info"] # turn info off in production
    environment:
      - DJANGO_SETTINGS_MODULE=rpl.settings
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - EMAIL_HOST_USER=rpl.etec@gmail.com
      - EMAIL_HOST_PASSWORD=wxfq qqau xvgp hhhy
      - DEFAULT_FROM_EMAIL=RPL <rpl.etec@gmail.com>
    depends_on:
      - redis
      - db
      - rpl

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - rpl
