# Generated by Django 5.1.6 on 2025-02-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('succes', models.BooleanField(blank=True, null=True)),
                ('code', models.TextField(default='', max_length=100000)),
                ('result', models.TextField(default='Codigo fallido o aun no testeado')),
            ],
        ),
    ]
