# Generated by Django 5.1.6 on 2025-03-07 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('succes', models.BooleanField(blank=True, null=True)),
                ('code', models.TextField(default='', max_length=100000)),
                ('result', models.TextField(default='Codigo fallido o aun no testeado')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exercises.exercise')),
            ],
        ),
    ]
