# Generated by Django 5.1.7 on 2025-03-15 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_user'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='account.profile'),
        ),
    ]
