# Generated by Django 5.1.7 on 2025-03-15 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_user'),
        ('submissions', '0002_codesubmission_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesubmission',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='account.profile'),
        ),
    ]
