# Generated by Django 5.1.6 on 2025-03-07 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excercises', '0002_alter_course_managers_alter_course_slug'),
        ('submissions', '0003_alter_codesubmission_excercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesubmission',
            name='excercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='excercises.excercise'),
        ),
    ]
