# Generated by Django 5.1.6 on 2025-03-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
