# Generated by Django 5.1.6 on 2025-03-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='course',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
