# Generated by Django 5.1.6 on 2025-03-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excercises', '0002_alter_course_managers_alter_course_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excercise',
            old_name='difiiculty',
            new_name='dificulty',
        ),
    ]
